//! Optimization contract manifest types.
//!
//! The manifest is a JSON string generated by the Lean OSLF pipeline
//! (`ExportOptManifest.lean`).  It provides formal provenance linking
//! runtime optimization flags to the Lean theorems that justify them.
//!
//! ## Architecture
//!
//! ```text
//! Lean (source of truth)
//!   OptimizationTheorems.lean  →  OptManifest.lean  →  ExportOptManifest.lean
//!                                                            ↓
//!                                                     manifest.json
//!                                                            ↓
//!                                                  include_str! in Rust
//!                                                            ↓
//!                                              RuntimeOptimizationContracts
//! ```
//!
//! The JSON manifest is embedded at compile time via `include_str!`.
//! The `RuntimeOptimizationContracts` booleans remain the fast runtime
//! gating mechanism; the manifest provides audit trail for CI/docs.

/// A single optimization contract entry extracted from the manifest.
#[derive(Debug, Clone)]
pub struct ManifestContract {
    pub id: String,
    pub name: String,
    pub lean_theorem: String,
    pub backend: String,
    pub precondition_type: String,
    pub precondition_condition: Option<String>,
    pub description: String,
}

/// A specialization pair extracted from the manifest.
#[derive(Debug, Clone)]
pub struct ManifestSpecPair {
    pub base_lang: String,
    pub ext_lang: String,
    pub lean_theorem: String,
}

/// Parsed optimization manifest.
#[derive(Debug, Clone)]
pub struct OptManifest {
    pub language: String,
    pub contracts: Vec<ManifestContract>,
    pub specialization_pairs: Vec<ManifestSpecPair>,
    pub congruence_policy: Vec<String>,
    /// The raw JSON source for display/audit.
    pub raw_json: String,
}

impl OptManifest {
    /// Parse a manifest from JSON string (minimal parser, no serde dependency).
    ///
    /// This is a simple extractor that handles the specific JSON format
    /// produced by `ExportOptManifest.lean`.  It is NOT a general JSON parser.
    pub fn from_json(json: &str) -> Option<Self> {
        let language = extract_string_field(json, "language")?;
        let contracts = extract_contracts(json);
        let specialization_pairs = extract_spec_pairs(json);
        let congruence_policy = extract_string_array(json, "congruence_policy");

        Some(OptManifest {
            language,
            contracts,
            specialization_pairs,
            congruence_policy,
            raw_json: json.to_string(),
        })
    }

    /// Check if a contract is present by ID.
    pub fn has_contract(&self, id: &str) -> bool {
        self.contracts.iter().any(|c| c.id == id)
    }

    /// Get the Lean theorem name backing a specific contract.
    pub fn theorem_for(&self, id: &str) -> Option<&str> {
        self.contracts
            .iter()
            .find(|c| c.id == id)
            .map(|c| c.lean_theorem.as_str())
    }

    /// Format a human-readable table of contracts for REPL display.
    pub fn display_table(&self) -> String {
        let mut lines = Vec::new();
        lines.push(format!(
            "Optimization Contracts for {} ({} contracts):",
            self.language,
            self.contracts.len()
        ));
        lines.push(String::new());

        let id_width = self
            .contracts
            .iter()
            .map(|c| c.id.len())
            .max()
            .unwrap_or(20);
        for c in &self.contracts {
            let backend_tag = if c.backend == "any_relation_env" {
                "[any backend]"
            } else {
                "[empty env]  "
            };
            lines.push(format!(
                "  {:<width$}  {}  {}",
                c.id,
                backend_tag,
                c.lean_theorem
                    .strip_prefix("Mettapedia.OSLF.Framework.OptimizationTheorems.")
                    .unwrap_or(&c.lean_theorem),
                width = id_width,
            ));
        }

        if !self.specialization_pairs.is_empty() {
            lines.push(String::new());
            lines.push("Specialization pairs:".to_string());
            for sp in &self.specialization_pairs {
                lines.push(format!("  {} → {}", sp.base_lang, sp.ext_lang));
            }
        }

        if !self.congruence_policy.is_empty() {
            lines.push(String::new());
            lines.push(format!("Congruence policy: {}", self.congruence_policy.join(", ")));
        }

        lines.join("\n")
    }
}

// --- Minimal JSON field extraction helpers ---

/// Extract a quoted string value for a given key.
fn extract_string_field(json: &str, key: &str) -> Option<String> {
    let pattern = format!("\"{}\": \"", key);
    let start = json.find(&pattern)? + pattern.len();
    let end = json[start..].find('"')? + start;
    Some(json[start..end].to_string())
}

/// Extract an array of strings for a given key.
fn extract_string_array(json: &str, key: &str) -> Vec<String> {
    let pattern = format!("\"{}\": [", key);
    let Some(start) = json.find(&pattern) else {
        return Vec::new();
    };
    let start = start + pattern.len();
    let Some(end) = json[start..].find(']') else {
        return Vec::new();
    };
    let slice = &json[start..start + end];
    slice
        .split('"')
        .enumerate()
        .filter(|(i, _)| i % 2 == 1)
        .map(|(_, s)| s.to_string())
        .collect()
}

/// Extract all contract objects from the JSON.
fn extract_contracts(json: &str) -> Vec<ManifestContract> {
    let Some(contracts_start) = json.find("\"contracts\": [") else {
        return Vec::new();
    };
    let contracts_section = &json[contracts_start..];

    let mut contracts = Vec::new();
    let mut pos = 0;

    while let Some(obj_start) = contracts_section[pos..].find('{') {
        let obj_start = pos + obj_start;
        let Some(obj_end) = contracts_section[obj_start..].find("\n      }") else {
            break;
        };
        let obj_end = obj_start + obj_end + "\n      }".len();
        let obj = &contracts_section[obj_start..obj_end];

        // Stop if we've left the contracts array
        if obj.contains("\"specialization_pairs\"") || obj.contains("\"congruence_policy\"") {
            break;
        }

        if let Some(c) = parse_contract_obj(obj) {
            contracts.push(c);
        }
        pos = obj_end;
    }

    contracts
}

/// Parse a single contract JSON object.
fn parse_contract_obj(obj: &str) -> Option<ManifestContract> {
    let id = extract_string_field(obj, "id")?;
    let name = extract_string_field(obj, "name")?;
    let lean_theorem = extract_string_field(obj, "lean_theorem")?;
    let backend = extract_string_field(obj, "backend")?;
    let description = extract_string_field(obj, "description")?;

    let precondition_type = extract_string_field(obj, "type").unwrap_or_default();
    let precondition_condition = extract_string_field(obj, "condition");

    Some(ManifestContract {
        id,
        name,
        lean_theorem,
        backend,
        precondition_type,
        precondition_condition,
        description,
    })
}

/// Extract specialization pair objects.
fn extract_spec_pairs(json: &str) -> Vec<ManifestSpecPair> {
    let Some(sp_start) = json.find("\"specialization_pairs\": [") else {
        return Vec::new();
    };
    let sp_section = &json[sp_start..];

    let mut pairs = Vec::new();
    let mut pos = 0;

    while let Some(obj_start) = sp_section[pos..].find('{') {
        let obj_start = pos + obj_start;
        let Some(obj_end) = sp_section[obj_start..].find('}') else {
            break;
        };
        let obj_end = obj_start + obj_end + 1;
        let obj = &sp_section[obj_start..obj_end];

        // Stop if we've left the spec pairs section
        if obj.contains("\"congruence_policy\"") {
            break;
        }

        if let (Some(base), Some(ext), Some(thm)) = (
            extract_string_field(obj, "base_lang"),
            extract_string_field(obj, "ext_lang"),
            extract_string_field(obj, "lean_theorem"),
        ) {
            pairs.push(ManifestSpecPair {
                base_lang: base,
                ext_lang: ext,
                lean_theorem: thm,
            });
        }
        pos = obj_end;
    }

    pairs
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_manifest() {
        let json = r#"{
  "language": "TestLang",
  "contracts": [
      {
        "id": "early_termination",
        "name": "Early Termination",
        "lean_theorem": "OptimizationTheorems.diamond_false_early_termination",
        "backend": "any_relation_env",
        "precondition": { "type": "runtime", "condition": "no successor" },
        "description": "Skip search when no diamond"
      }
    ],
  "specialization_pairs": [
      {
        "base_lang": "rhoCalc",
        "ext_lang": "rhoCalcSetExt",
        "lean_theorem": "specialization_preserves_reduction"
      }
    ],
  "congruence_policy": ["Vec", "HashBag"]
}"#;

        let manifest = OptManifest::from_json(json).expect("should parse");
        assert_eq!(manifest.language, "TestLang");
        assert_eq!(manifest.contracts.len(), 1);
        assert_eq!(manifest.contracts[0].id, "early_termination");
        assert_eq!(
            manifest.contracts[0].lean_theorem,
            "OptimizationTheorems.diamond_false_early_termination"
        );
        assert_eq!(manifest.specialization_pairs.len(), 1);
        assert_eq!(manifest.specialization_pairs[0].base_lang, "rhoCalc");
        assert_eq!(manifest.congruence_policy, vec!["Vec", "HashBag"]);
        assert!(manifest.has_contract("early_termination"));
        assert!(!manifest.has_contract("nonexistent"));
    }
}
