//! Extracts `language! { ... }` bodies from languages/src/*.rs and generates
//! language_grammar! invocations so lang-gen stays in sync without hand-editing.

use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let src_dir = Path::new(&manifest_dir).join("..").join("src");

    let mut modules_bodies: Vec<(String, String)> = Vec::new();

    let entries = fs::read_dir(&src_dir)
        .unwrap_or_else(|e| panic!("lang-gen: cannot read {}: {}", src_dir.display(), e));

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().map_or(true, |e| e != "rs") {
            continue;
        }
        let stem = match path.file_stem().and_then(|s| s.to_str()) {
            Some(s) => s.to_string(),
            None => continue,
        };
        if stem == "lib" || stem == "space" {
            continue;
        }

        let content = match fs::read_to_string(&path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let file = match syn::parse_file(&content) {
            Ok(f) => f,
            Err(_) => continue,
        };

        for item in &file.items {
            let syn::Item::Macro(item_macro) = item else {
                continue;
            };
            let segs = &item_macro.mac.path.segments;
            let is_language = segs.last().map_or(false, |s| s.ident == "language");
            if !is_language {
                continue;
            }

            let body = item_macro.mac.tokens.to_string();
            modules_bodies.push((stem, body));
            break;
        }
    }

    modules_bodies.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::from(
        "// Auto-generated by lang-gen/build.rs — do not edit\n\
         use mettail_macros::language_grammar;\n\n",
    );
    for (_stem, body) in &modules_bodies {
        generated.push_str("language_grammar! {\n");
        generated.push_str(body);
        generated.push_str("\n}\n\n");
    }

    let generated_path = Path::new(&out_dir).join("generated.rs");
    fs::write(&generated_path, generated).expect("write generated.rs");

    println!("cargo:rerun-if-changed=../src");
}
