//! Shared tree-sitter surface parser for `.metta` files.
//!
//! This module provides artifact-driven parsing via Lean-exported tree-sitter
//! grammars. It is the single shared parse path for all MeTTa surface syntax.
//! Do not add hand-written parsers — see Parser Policy in CLAUDE.md.

use tree_sitter::{Language as TSLanguage, Node as TSNode, Parser as TSParser};

use crate::sexpr::SExpr;

// FFI symbols generated by build.rs from Lean-exported grammar artifacts.
extern "C" {
    fn tree_sitter_metta_he() -> TSLanguage;
    fn tree_sitter_metta_petta() -> TSLanguage;
}

/// Get the compiled tree-sitter language for a given dialect key.
pub fn tree_sitter_language_for_dialect(dialect_key: &str) -> Result<TSLanguage, String> {
    match dialect_key {
        "he" => Ok(unsafe { tree_sitter_metta_he() }),
        "petta" => Ok(unsafe { tree_sitter_metta_petta() }),
        other => Err(format!("unsupported embedded tree-sitter dialect '{other}'")),
    }
}

/// Parse a single top-level `.metta` form via tree-sitter.
///
/// Returns `(is_eval_form, sexpr)` where `is_eval_form` is true when the input
/// is a `!(expr)` evaluation directive.
pub fn parse_sexpr_via_tree_sitter(
    dialect_key: &str,
    input: &str,
) -> Result<(bool, SExpr), String> {
    let mut parser = TSParser::new();
    let language = tree_sitter_language_for_dialect(dialect_key)?;
    parser
        .set_language(&language)
        .map_err(|e| format!("failed to set tree-sitter language '{dialect_key}': {e}"))?;
    let tree = parser
        .parse(input, None)
        .ok_or_else(|| "tree-sitter returned no parse tree".to_string())?;
    let root = tree.root_node();
    if root.has_error() || root.is_error() {
        return Err(format!(
            "tree-sitter parse error in '{}': input contains syntax errors",
            input.chars().take(80).collect::<String>()
        ));
    }
    decode_single_top(root, input)
}

/// Parse a multi-statement `.metta` source via tree-sitter.
///
/// Returns a list of `(is_eval_form, sexpr)` for each top-level form.
/// This is the entry point for parsing entire `.metta` files.
pub fn parse_many_sexprs(dialect_key: &str, input: &str) -> Result<Vec<(bool, SExpr)>, String> {
    let mut parser = TSParser::new();
    let language = tree_sitter_language_for_dialect(dialect_key)?;
    parser
        .set_language(&language)
        .map_err(|e| format!("failed to set tree-sitter language '{dialect_key}': {e}"))?;
    let tree = parser
        .parse(input, None)
        .ok_or_else(|| "tree-sitter returned no parse tree".to_string())?;
    let root = tree.root_node();
    if root.has_error() || root.is_error() {
        return Err(format!(
            "tree-sitter parse error: input contains syntax errors near '{}'",
            input.chars().take(80).collect::<String>()
        ));
    }
    decode_all_tops(root, input)
}

// ── Internal decode helpers ──────────────────────────────────────────────────

fn decode_single_top(root: TSNode<'_>, source: &str) -> Result<(bool, SExpr), String> {
    let mut tops = Vec::new();
    for idx in 0..root.named_child_count() {
        if let Some(child) = root.named_child(idx) {
            if matches!(child.kind(), "eval_form" | "atom") {
                tops.push(child);
            }
        }
    }

    if tops.is_empty() {
        return Err("tree-sitter parse produced no top-level form".to_string());
    }
    if tops.len() != 1 {
        return Err(format!(
            "tree-sitter parse produced {} top-level forms; expected exactly 1",
            tops.len()
        ));
    }

    decode_top_node(tops[0], source)
}

fn decode_all_tops(root: TSNode<'_>, source: &str) -> Result<Vec<(bool, SExpr)>, String> {
    let mut results = Vec::new();
    for idx in 0..root.named_child_count() {
        if let Some(child) = root.named_child(idx) {
            if matches!(child.kind(), "eval_form" | "atom") {
                results.push(decode_top_node(child, source)?);
            }
        }
    }
    Ok(results)
}

fn decode_top_node(top: TSNode<'_>, source: &str) -> Result<(bool, SExpr), String> {
    if top.kind() == "eval_form" {
        let atom = first_named_child_of_kind(top, "atom")
            .ok_or_else(|| "tree-sitter eval_form missing atom child".to_string())?;
        return Ok((true, decode_atom(atom, source)?));
    }
    Ok((false, decode_atom(top, source)?))
}

fn first_named_child_of_kind<'a>(node: TSNode<'a>, kind: &str) -> Option<TSNode<'a>> {
    (0..node.named_child_count())
        .filter_map(|idx| node.named_child(idx))
        .find(|child| child.kind() == kind)
}

fn decode_atom(node: TSNode<'_>, source: &str) -> Result<SExpr, String> {
    match node.kind() {
        "atom" => {
            let child = (0..node.named_child_count())
                .filter_map(|idx| node.named_child(idx))
                .find(|child| child.kind() != "comment")
                .ok_or_else(|| "tree-sitter atom node has no concrete child".to_string())?;
            decode_atom(child, source)
        },
        "symbol" | "variable" | "string" => {
            let text = node
                .utf8_text(source.as_bytes())
                .map_err(|e| format!("invalid utf8 span from tree-sitter: {e}"))?;
            Ok(SExpr::Atom(text.to_string()))
        },
        "list" => {
            let mut items = Vec::new();
            for idx in 0..node.named_child_count() {
                if let Some(child) = node.named_child(idx) {
                    if child.kind() == "atom" {
                        items.push(decode_atom(child, source)?);
                    }
                }
            }
            Ok(SExpr::List(items))
        },
        other => Err(format!("unsupported tree-sitter atom node kind '{other}'")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_atom() {
        let (is_eval, sexpr) = parse_sexpr_via_tree_sitter("petta", "foo").unwrap();
        assert!(!is_eval);
        assert_eq!(sexpr, SExpr::Atom("foo".into()));
    }

    #[test]
    fn parse_eval_form() {
        let (is_eval, sexpr) = parse_sexpr_via_tree_sitter("petta", "!(+ 1 2)").unwrap();
        assert!(is_eval);
        assert_eq!(
            sexpr,
            SExpr::List(vec![
                SExpr::Atom("+".into()),
                SExpr::Atom("1".into()),
                SExpr::Atom("2".into()),
            ])
        );
    }

    #[test]
    fn parse_variable() {
        let (is_eval, sexpr) = parse_sexpr_via_tree_sitter("petta", "$x").unwrap();
        assert!(!is_eval);
        assert_eq!(sexpr, SExpr::Atom("$x".into()));
    }

    #[test]
    fn parse_nested_list() {
        let (_, sexpr) = parse_sexpr_via_tree_sitter("petta", "(= (f $x) (+ $x 1))").unwrap();
        assert_eq!(
            sexpr,
            SExpr::List(vec![
                SExpr::Atom("=".into()),
                SExpr::List(vec![SExpr::Atom("f".into()), SExpr::Atom("$x".into())]),
                SExpr::List(vec![
                    SExpr::Atom("+".into()),
                    SExpr::Atom("$x".into()),
                    SExpr::Atom("1".into()),
                ]),
            ])
        );
    }

    #[test]
    fn parse_many_forms() {
        let input = "(= (f $x) $x)\n!(f 42)\n";
        let forms = parse_many_sexprs("petta", input).unwrap();
        assert_eq!(forms.len(), 2);
        assert!(!forms[0].0); // rule, not eval
        assert!(forms[1].0); // eval form
    }

    #[test]
    fn parse_with_comment() {
        let input = "; this is a comment\n!(+ 1 2)";
        let forms = parse_many_sexprs("petta", input).unwrap();
        assert_eq!(forms.len(), 1);
        assert!(forms[0].0);
    }

    #[test]
    fn parse_he_dialect() {
        let (is_eval, sexpr) = parse_sexpr_via_tree_sitter("he", "!(+ 1 2)").unwrap();
        assert!(is_eval);
        assert_eq!(
            sexpr,
            SExpr::List(vec![
                SExpr::Atom("+".into()),
                SExpr::Atom("1".into()),
                SExpr::Atom("2".into()),
            ])
        );
    }

    #[test]
    fn parse_empty_list() {
        let (_, sexpr) = parse_sexpr_via_tree_sitter("petta", "()").unwrap();
        assert_eq!(sexpr, SExpr::List(vec![]));
    }
}
